Update patch set 1
Patch Set 1:

I'm getting following error when provisioning cirros image via packstack. Looking at the update, glance provider has been changed, so we should update packstack accordingly: 

Error: Could not prefetch glance_image provider 'glance': File: /etc/glance/glance-api.conf does not contain all required sections

Patch-set: 1
Reviewer: Martin Magr <1001151@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=0