Update mongodb to fe562b86f388a6d107bb1f3cb3b32a3978f59c2a
commit fe562b86f388a6d107bb1f3cb3b32a3978f59c2a
Merge: 7651365 34a9f7a
Author: Colleen Murphy <cmurphy@users.noreply.github.com>
Date:   Wed Nov 26 10:39:54 2014 -0800

    Merge pull request #149 from mhaskel/typo

    typo fix

commit 34a9f7aea3d513282b3de2190709c61522554dcd
Author: Morgan Haskel <morgan@puppetlabs.com>
Date:   Wed Nov 26 13:37:36 2014 -0500

    typo fix

    The lack of trailing commas in json strikes again.

commit 7651365ec5cdcd74909ff79317426b1b7d55d1a9
Merge: 8da88be aeb3bfe
Author: Travis Fields <cyberious@users.noreply.github.com>
Date:   Fri Nov 21 19:25:43 2014 -0500

    Merge pull request #146 from mhaskel/0.9.0-prep

    0.9.0 prep

commit aeb3bfe100f94048a20c1d75013bc4131a27f1ff
Author: Morgan Haskel <morgan@puppetlabs.com>
Date:   Fri Nov 21 19:23:08 2014 -0500

    0.9.0 prep

commit 8da88bed9f4d59e6582a2bd23c2c5ddd0a5d954d
Merge: d414ae5 ac0671e
Author: Morgan Haskel <morgan@puppetlabs.com>
Date:   Fri Nov 21 19:15:01 2014 -0500

    Merge pull request #145 from laurenrother/summary

    Add metadata summary to Modulefile per FM-1523

commit ac0671e89764f59c16deefe0cde803a6856c2435
Author: Lauren Rother <lauren.rother@puppetlabs.com>
Date:   Thu Nov 20 15:57:32 2014 -0800

    Add metadata summary to Modulefile per FM-1523

commit d414ae577777ed288bab7485c8db73638c21f7ba
Merge: a4d5936 a1c73c8
Author: Hunter Haugen <hunter@puppetlabs.com>
Date:   Thu Nov 20 10:53:37 2014 -0800

    Merge pull request #129 from leopoiroux/master

    Added "quiet" on mongo.conf

commit a4d593690b5fad43a0688e5848b2e2b7c6ab5b88
Merge: 75d5da2 c8bbac7
Author: Morgan Haskel <morgan@puppetlabs.com>
Date:   Thu Nov 20 13:40:58 2014 -0500

    Merge pull request #142 from fnaard/fix_typo_in_readme

    Fix typo in README so that puppet code formatting gets applied.

commit 75d5da27b32c1929c21f2a7cd1c8640dbdb2f8a4
Merge: d8134e3 407093c
Author: Hunter Haugen <hunter@puppetlabs.com>
Date:   Thu Nov 20 10:40:48 2014 -0800

    Merge pull request #144 from synyx/master

    Fixed params.pp

commit d8134e3cfd164aeca851d4a7abcb28edcfb750dc
Merge: 3dd7699 3fc5835
Author: Hunter Haugen <hunter@puppetlabs.com>
Date:   Thu Nov 20 10:38:03 2014 -0800

    Merge pull request #138 from ninech/auth

    Workaround to enable mongodb_user/database to work with authentication.

commit 407093c32d6a61a8c6e908e8233db4d1e985b123
Author: Johannes Graf <graf@synyx.de>
Date:   Thu Nov 13 18:12:48 2014 +0100

    Fixed params.pp

    There are two issues on Debian based distributions using
    mongodb.org packages:

    ```puppet
    class {'::mongodb::globals':
    manage_package_repo => true,
    }->
    class {'::mongodb::server':}->
    class {'::mongodb::client':}
    ```

    ### $config is undef for mongodb config unter /etc

    Error: Parameter path failed on File[undef]: File paths must be fully qualified, not 'undef' at /etc/puppet/modules/mongodb/manifests/server/config.pp:83

    ### $service_name is `mongodb` instead of `mongod`

    Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Could not evaluate: Could not find init script or upstart conf file for 'mongodb'
    Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Failed to call refresh: Could not find init script or upstart conf file for 'mongodb'
    Error: /Stage[main]/Mongodb::Server::Service/Service[mongodb]: Could not find init script or upstart conf file for 'mongodb'
    Warning: /Stage[main]/Mongodb::Server::Service/Mongodb_conn_validator[mongodb]: Skipping because of failed dependencies
    Warning: /Stage[main]/Mongodb::Server/Anchor[mongodb::server::end]: Skipping because of failed dependencies

commit 3dd76996523b0ebf95a8655d781bc8752040eb2b
Merge: 0518f86 5e22985
Author: Hunter Haugen <hunter@puppetlabs.com>
Date:   Wed Nov 12 12:26:06 2014 -0800

    Merge pull request #139 from amoswood/master

    Mongo 2.6 version and config support

commit c8bbac708385e698418666c44edce3b148126d17
Author: Gabriel M Schuyler <gabe@puppetlabs.com>
Date:   Mon Oct 27 15:30:58 2014 -0700

    Fix typo in README so that puppet code formatting gets applied.

commit 3fc583511dde45c7e30126e0480a2700b2ad1206
Author: Marius Rieder <marius.rieder@durchmesser.ch>
Date:   Mon Oct 6 12:31:32 2014 +0200

    Fix spec for ruby 1.8

commit 5e229857c29bd44c9d812a21bed69098bf670a6a
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Wed Sep 24 11:23:33 2014 -0700

    params and globals improvements and clean-up for 2.6 support

commit c43964f13e3d11be8c0becc34a7a2fbd397d7963
Author: Marius Rieder <marius.rieder@durchmesser.ch>
Date:   Tue Sep 23 14:39:25 2014 +0200

    Document the new mongodb_user parameter.

commit ecbc9e8db055ce96421a9a1af710b15b3cc60e62
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Wed Sep 17 13:17:21 2014 +0200

    Set version to 2.6.x for spec

commit 9aacef2bc18ff37b5a81403af41b21b89dd9ceb0
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Wed Sep 17 13:13:33 2014 +0200

    Add Mongodb 2.4.x compatibility for mongodb_user

commit ef47f9e788d222656e7c9fb45ef894ac16583bcb
Author: Marius Rieder <marius.rieder@durchmesser.ch>
Date:   Wed Sep 17 07:46:42 2014 +0200

    Fix specs for improved type providers

commit f63c781841684657df54e9546d12812e35bb66a1
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Tue Sep 16 10:39:32 2014 +0200

    Reimplement mongodb_database provider based on Puppet::Provider::Mongodb

commit f66e963fb0f9092f07670c20a8465de86a2d787d
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Tue Sep 16 10:19:40 2014 +0200

    Reimplement mongodb_user provider

    Based on Puppet::Provider::Mongodb for mongodb 2.6.x

commit c3662503b9c45fcb792badb1cbb9c72556acef3b
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Tue Sep 16 10:18:23 2014 +0200

    Add a username property to mongodb_user.

    This allows to have users with the same name in different databases.

commit f8732d6b512b793c34524393e0ed4d596e22589d
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Tue Sep 16 10:15:40 2014 +0200

    Addapt mongodb types to allow resource listing.

    database is a property not a parameter

    database default to test, not to fail anymore
    password_hash default to false, not to fail anymore

commit 31f3baa8539dd91b445f2b9bb4fc8c40d5e3a544
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Mon Sep 22 10:13:48 2014 -0700

    redux: revert key_server in apt repo

commit 50b46f7dc83da8d7980d8130d30be32bf0a87963
Merge: a138a1e 88c7f3c
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Mon Sep 22 10:09:53 2014 -0700

    Merge branch 'master' of https://github.com/amoswood/puppetlabs-mongodb

commit a138a1e0431fa348f274a4d6807933c22d4403bc
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Mon Sep 22 10:09:49 2014 -0700

    reset key_server to use "hkp"

commit b1d2779ab1bd3b3f6858e6714c3147c901b747ef
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Fri Sep 12 10:06:34 2014 -0500

    v2.6 config file template; custom config template

commit 4ec92eaad7eab8d88b0fe83f9e6af146629bd64c
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Wed Jul 23 12:28:03 2014 -0500

    change key_server to not brake apt

commit 2bbf8a7ee6ada5274d86913fa06c04131f68e9ed
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Mon Jun 23 09:49:11 2014 -0500

    Fixed puppet management of configuration file

    In versions 2.4 and 2.6, the default configuration file name for Debian
    changed and was not captured in the params.pp file.

commit 3e7176e099094f2a5608be2dbfd36a00c6301ec6
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Fri Jun 20 16:28:23 2014 +0000

    allowed server and client to properly use globals::version. Included Debian support for pre 2.6 and post 2.6 package names

commit d73f8731324adc72c71af533590e1878d9e7ab8a
Author: Marius Rieder <marius.rieder@nine.ch>
Date:   Tue Sep 16 09:17:58 2014 +0200

    Add Puppet::Provider::Mongodb for shared provider code.

commit 88c7f3c8f069ec815524031916c9d857ca1ca191
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Fri Sep 12 10:06:34 2014 -0500

    v2.6 config file template; custom config template

commit a2c0fa5a4c389579db8589736047cb098c6353cc
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Wed Jul 23 12:28:03 2014 -0500

    change key_server to not brake apt

commit 5023e9b2339cd78c56484b5aa6bd4752ca931cc9
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Mon Jun 23 09:49:11 2014 -0500

    Fixed puppet management of configuration file

    In versions 2.4 and 2.6, the default configuration file name for Debian
    changed and was not captured in the params.pp file.

commit 2b5b066a3d2652102e897ca7978164afa5426834
Author: Amos Wood <amos.wood@lifeway.com>
Date:   Fri Jun 20 16:28:23 2014 +0000

    allowed server and client to properly use globals::version. Included Debian support for pre 2.6 and post 2.6 package names

commit a1c73c87c3b76283e41ed9cf08a6782c4aeda1aa
Author: Léo POIROUX <leo.poiroux@gmail.com>
Date:   Fri Jul 11 14:37:34 2014 +0200

    Update README.md

commit 65fb18859752bbbbde51e7d4cc2b3ce17453445d
Author: Léo POIROUX <leo.poiroux@gmail.com>
Date:   Wed Jul 9 15:40:27 2014 +0200

    Update mongodb.conf.erb

commit 4484d742c18677c29b1843e70c1037b97f81de5b
Author: Léo POIROUX <leo.poiroux@gmail.com>
Date:   Wed Jul 9 15:38:41 2014 +0200

    Update server.pp

commit fde59d079da148f9259f92d71b3f6221dafb8659
Author: Léo POIROUX <leo.poiroux@gmail.com>
Date:   Wed Jul 9 15:37:14 2014 +0200

    Update config.pp

commit cbcb251b09cdb4f7a1587d86999b21dbc4e5d765
Author: Léo POIROUX <leo.poiroux@gmail.com>
Date:   Wed Jul 9 15:36:02 2014 +0200

    Update init.pp