Update patch set 2
Patch Set 2:

I'm getting following error when provisioning cirros image via packstack. Looking at the update, glance provider has been changed, so we should update packstack accordingly: 

Error: Could not prefetch glance_image provider 'glance': File: /etc/glance/glance-api.conf does not contain all required sections

Patch-set: 2